# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeStatusline < Formula
  desc "Configurable status line for Claude Code"
  homepage "https://github.com/frank-bee/claude-statusline"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frank-bee/claude-statusline/releases/download/v0.10.0/claude-statusline_0.10.0_darwin_amd64.tar.gz"
      sha256 "7b335fd33bad07dd38fc9caf003921670364decb3a1a464f326f3188039f04df"

      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frank-bee/claude-statusline/releases/download/v0.10.0/claude-statusline_0.10.0_darwin_arm64.tar.gz"
      sha256 "c315a7d6dea180cf99b3ba532240a7a2c6067cbf92faa6e4280645080c982d61"

      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frank-bee/claude-statusline/releases/download/v0.10.0/claude-statusline_0.10.0_linux_amd64.tar.gz"
      sha256 "6e5b74ad74e03b85f06abcfbcbe408310e61ae02e4cc118fcf25b3ff952a2f10"
      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frank-bee/claude-statusline/releases/download/v0.10.0/claude-statusline_0.10.0_linux_arm64.tar.gz"
      sha256 "6107cda7449c0324155ecdf898fed7c589bed2536c77293b9337aa474422cf48"
      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
  end
end
