# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeStatusline < Formula
  desc "Configurable status line for Claude Code"
  homepage "https://github.com/frank-bee/claude-statusline"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frank-bee/claude-statusline/releases/download/v0.11.0/claude-statusline_0.11.0_darwin_amd64.tar.gz"
      sha256 "c90c525062c25df47c14edcad306a62f041d8d24302ea8a121d62a295219241e"

      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frank-bee/claude-statusline/releases/download/v0.11.0/claude-statusline_0.11.0_darwin_arm64.tar.gz"
      sha256 "864431e6b0118d4bb30bafdd5268285e92479936386cc03f5af8ddd6382e96a5"

      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frank-bee/claude-statusline/releases/download/v0.11.0/claude-statusline_0.11.0_linux_amd64.tar.gz"
      sha256 "19ff853e87f77587ab04b89eafa8a7cfa4aaa0220252d93c4b49db392fea80a0"
      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frank-bee/claude-statusline/releases/download/v0.11.0/claude-statusline_0.11.0_linux_arm64.tar.gz"
      sha256 "8e713abaf3309e697b289df652f268e09ed556536c7b1c4cf90da059979c4881"
      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
  end
end
