# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeStatusline < Formula
  desc "Configurable status line for Claude Code"
  homepage "https://github.com/frank-bee/claude-statusline"
  version "0.10.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frank-bee/claude-statusline/releases/download/v0.10.1/claude-statusline_0.10.1_darwin_amd64.tar.gz"
      sha256 "9b3c0e33a1e0abc43642340b81e13f19d20a0e1f2db85954be1f1fc3d070ff4c"

      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frank-bee/claude-statusline/releases/download/v0.10.1/claude-statusline_0.10.1_darwin_arm64.tar.gz"
      sha256 "84b60d2b853d672520a3040051589d18c38b7cdcadf4f4e9d95fe49e183115da"

      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frank-bee/claude-statusline/releases/download/v0.10.1/claude-statusline_0.10.1_linux_amd64.tar.gz"
      sha256 "190de929cb5b37a90d80773b67bb1fdaad1d22f3247b6819fcf1a10ca0a7b390"
      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frank-bee/claude-statusline/releases/download/v0.10.1/claude-statusline_0.10.1_linux_arm64.tar.gz"
      sha256 "52b22f83b92eacc43f0fb6e15c1904e9f88591925375051227d07e7d1d7a24ae"
      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
  end
end
