# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeStatusline < Formula
  desc "Configurable status line for Claude Code"
  homepage "https://github.com/frank-bee/claude-statusline"
  version "0.11.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frank-bee/claude-statusline/releases/download/v0.11.1/claude-statusline_0.11.1_darwin_amd64.tar.gz"
      sha256 "ffdcfea00d42f8e1615422f910a6061022e86d51cb47999666a8f35cbcfdf765"

      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frank-bee/claude-statusline/releases/download/v0.11.1/claude-statusline_0.11.1_darwin_arm64.tar.gz"
      sha256 "44c246119bb07f36d672e7ad775a3bad8dd3a5490b48f660a9920266d18e28b0"

      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frank-bee/claude-statusline/releases/download/v0.11.1/claude-statusline_0.11.1_linux_amd64.tar.gz"
      sha256 "77a013d3329239b603383058f25befba9e7df9173349eb27cfe7425060dc758f"
      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frank-bee/claude-statusline/releases/download/v0.11.1/claude-statusline_0.11.1_linux_arm64.tar.gz"
      sha256 "8a368d79c9e19af4b62dce2c72a28767fa1182034c8298de40606e4b4cb18c22"
      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
  end
end
